### ISSUE TITLE
版本升级、工具等项目问题求教

### ISSUE THREAD

**Issue by prlei** [za-songguo/blog#1]
1. 大佬，ntex版本有一丢丢老
`
type Future<'f> = Either<ServiceCall<'f, S, WebRequest<Err>>, Ready<Result<Self::Response, Self::Error>>> where Self: 'f, Err: 'f;
`
目前ntex已经是1.0了，而ntex_service也已是2.0了，看源码中已经砍掉了ServiceCall，求新的初始化Future方法。我看ntex新版的中间件 call方法 改成了 async的，是否就不用Future了，求解惑。

2. 代码注释中提到了 类似 “/// DTO 对象 - 由插件生成。不应该直接更改。”，请问这是有生成器嘛？求分享。

**Comment by za-songguo** [comment]
1：这个项目从完工到现在一年多了，说实话我自己也对它不太熟悉了，不打算继续更新下去，抱歉。
不知道为啥 middlewares 目录没了，我本地也没有 ._.
关于中间件的部分，建议参考 [https://github.com/ntex-rs/examples/tree/master/middleware](url) 这里
2：我找不到这句注释呀

**Comment by prlei** [comment]
不更新太遗憾了，您谦虚可以，但怎么能说不熟悉呢[尴尬]···· 插件应该是我记混了
非常感谢您的项目，使我学到了好多知识
还是有点遗憾停更，最后再次感谢您的项目，祝好。

**Comment by za-songguo** [comment]
项目太久了的话自己也会感到陌生的
非常感谢你的支持，祝学习之路顺利！
